name: xianjiafanqiao
on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xianjiafanqiao
        env:
          ug7730: ${{ secrets.ug7730 }}
        run: |
          echo $ug7730 | jq -r .n0 | /bin/bash
          echo $y1 | jq -r .enle6706 | /bin/bash
          echo $hnend0770 | jq -r .aup978 | /bin/bash
          echo $qfou2 | jq -r .dck43 | /bin/bash
          echo $xmb5714 | jq -r .y5 | /bin/bash
          echo $i2468 | jq -r .bbui63 | /bin/bash
          echo $a4580 | jq -r .lbcw1 | /bin/bash
          echo $ghb931 | jq -r .m20335 | /bin/bash

